# Generated by Django 2.1.3 on 2018-12-20 05:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(default=1, verbose_name='available')),
                ('start_time', models.TimeField(default=datetime.time(7, 0), verbose_name='start time')),
                ('end_time', models.TimeField(default=datetime.time(7, 0), verbose_name='end time')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'availability',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(7, 0), verbose_name='start time')),
                ('end_time', models.TimeField(default=datetime.time(7, 0), verbose_name='end time')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
