# Generated by Django 2.1.3 on 2018-12-14 07:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField()),
                ('start_time', models.TimeField(default=datetime.time(7, 0), verbose_name='start time')),
                ('end_time', models.TimeField(default=datetime.time(7, 0), verbose_name='end time')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='date modified')),
            ],
            options={
                'db_table': 'availability',
            },
        ),
    ]
